language: python
python:
  - "3.5"
env:
  - DJANGO_VERSION=1.9.10
  - DJANGO_VERSION=1.10.1
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -e . --use-mirrors
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=simple_import manage.py test
after_success:
  coveralls
sudo: false
